name: mlfrag
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # Python version
  - python=3.11

  # Core scientific computing
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0

  # Machine learning (conda-forge)
  - scikit-learn>=1.3.0
  - xgboost>=2.0.0
  - lightgbm>=4.0.0

  # PyTorch (from pytorch channel)
  - pytorch>=2.0.0
  - pytorch-cuda=11.8  # Or pytorch-cuda=12.1 for CUDA 12

  # Chemistry
  - rdkit>=2023.3.1

  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.14.0

  # Utilities
  - tqdm>=4.65.0
  - pyyaml>=6.0
  - joblib>=1.3.0

  # Development tools
  - pytest>=7.4.0
  - pytest-cov>=4.1.0
  - black>=23.7.0
  - mypy>=1.4.0
  - isort>=5.12.0
  - jupyter>=1.0.0
  - ipykernel>=6.25.0

  # pip-only dependencies
  - pip>=23.0
  - pip:
    - catboost>=1.2.0
    - loguru>=0.7.0
    - ruff>=0.0.280
    # Uncomment for advanced features:
    # - chemprop>=1.6.0
    # - botorch>=0.9.0
    # - gpytorch>=1.11
    # - shap>=0.42.0

# Installation instructions:
# 1. Create environment: conda env create -f environment.yml
# 2. Activate: conda activate mlfrag
# 3. Install package in editable mode: pip install -e .
# 4. For all features: pip install -e ".[all]"
