# ADMET Model Configuration
# Example configuration for training multi-task ADMET prediction models

# Model Architecture
model_type: xgboost  # Options: random_forest, xgboost, gradient_boosting
fingerprint_type: morgan  # Options: morgan, maccs, rdkit, avalon
fingerprint_radius: 2
fingerprint_bits: 2048
use_descriptors: false

# Training Parameters
n_estimators: 100
max_depth: 6  # None for random_forest (unlimited), 6 for xgboost
learning_rate: 0.1
test_size: 0.2
random_state: 42
n_jobs: -1  # Use all available cores

# Multi-task Settings
properties:
  - solubility
  - logp
  - clearance

# Optional: Task-specific weights for multi-task learning
task_weights:
  solubility: 1.0
  logp: 1.0
  clearance: 1.5  # Higher weight for harder task

# Validation
cv_folds: 5
early_stopping_rounds: 50

# Output
save_checkpoints: true
checkpoint_dir: models/checkpoints
